builds:
- env: [CGO_ENABLED=0]
  goos:
  - linux
  - windows
  - darwin
  goarch:
  - amd64
  - arm64
dockers:
- image_templates: ["ghcr.io/huseyinbabal/{{ .ProjectName }}:{{ .Version }}-amd64"]
  dockerfile: Dockerfile
  use: buildx
  build_flag_templates:
  - --platform=linux/amd64
  - --label=org.opencontainers.image.title={{ .ProjectName }}
  - --label=org.opencontainers.image.description={{ .ProjectName }}
  - --label=org.opencontainers.image.url=https://github.com/huseyinbabal/{{ .ProjectName }}
  - --label=org.opencontainers.image.source=https://github.com/huseyinbabal/{{ .ProjectName }}
  - --label=org.opencontainers.image.version={{ .Version }}
  - --label=org.opencontainers.image.revision={{ .FullCommit }}
  - --label=org.opencontainers.image.licenses=MIT
- image_templates: ["ghcr.io/huseyinbabal/{{ .ProjectName }}:{{ .Version }}-arm64v8"]
  goarch: arm64
  dockerfile: Dockerfile
  use: buildx
  build_flag_templates:
  - --platform=linux/arm64/v8
  - --label=org.opencontainers.image.title={{ .ProjectName }}
  - --label=org.opencontainers.image.description={{ .ProjectName }}
  - --label=org.opencontainers.image.url=https://github.com/huseyinbabal/{{ .ProjectName }}
  - --label=org.opencontainers.image.source=https://github.com/huseyinbabal/{{ .ProjectName }}
  - --label=org.opencontainers.image.version={{ .Version }}
  - --label=org.opencontainers.image.revision={{ .FullCommit }}
  - --label=org.opencontainers.image.licenses=MIT
docker_manifests:
- name_template: ghcr.io/huseyinbabal/{{ .ProjectName }}:{{ .Version }}
  image_templates:
  - ghcr.io/huseyinbabal/{{ .ProjectName }}:{{ .Version }}-amd64
  - ghcr.io/huseyinbabal/{{ .ProjectName }}:{{ .Version }}-arm64v8
- name_template: ghcr.io/huseyinbabal/{{ .ProjectName }}:latest
  image_templates:
  - ghcr.io/huseyinbabal/{{ .ProjectName }}:{{ .Version }}-amd64
  - ghcr.io/huseyinbabal/{{ .ProjectName }}:{{ .Version }}-arm64v8
